### ISSUE TITLE
Could not load the plugin

### ISSUE THREAD

**Issue by Grimerlin** [haveric/StackableItems#103]
Spigot version: 1.7.9-R0.3 (#1543)
StackableItems version:  1.0
Vault version: 1.4.1
Error: http://pastebin.com/S7rUaTMw

Isn't the plugin compatible from 1.7.9 to 1.8.1?

**Comment by haveric** [comment]
What version of Java are you using?  I normally compile with Java 6 to make it compatible for everyone, but I had to do a last minute rebuild on a different machine meaning that it may have been compiled with a newer Java version.

Either way, you should always be using the newest Java build for a server to get the best performance out of it.  I would suggest updating to Java 8.

**Comment by Grimerlin** [comment]
I'm using Java 7 now. I will update to Java 8.

**Comment by haveric** [comment]
Future versions will support Java 6-8. I'll look into getting my alternate dev machine setup to build correctly in the future, but hopefully I won't have to use it again.
