### ISSUE TITLE
Duplication Bug

### ISSUE THREAD

**Issue by Grimerlin** [haveric/StackableItems#104]
Spigot version: 1.7.9-R0.3 (#1543)
StackableItems version: 1.0
Bug: If you put the crafting materials of an item, defined in items.yml and so handled by the plugin, in the crafting table and you click to craft it dragging another item in the cursor you duplicate that item and you don't get the crafted item.
Example: I try to craft a door (I defined that a door can have a stack of 64) and I click with a diamond sword in the cursor. What happen is that I get two diamond swords, the wood used in the crafting process disappear and I don't get the door I wanted to craft.
Note: there was this bug also in the previous plugin version.

**Comment by haveric** [comment]
I'm going to do a bit more testing for this tomorrow just to make sure this doesn't break anything.
