### ISSUE TITLE
Chests and increased stacks (1.8)

### ISSUE THREAD

**Issue by bunnypig** [haveric/StackableItems#105]
Hello.

If this has already been answered some where I'm deeply sorry.

Whenever I set a stack's limit to 120 it shows in inventory. But when I try to put that stack in a chest it goes back to 64 (although it actually contains 120 items in that stack). If I take the stack back out of the case, it changes the value to 120.

Can this be fixed? Sincerely, BunnyPig.

**Comment by haveric** [comment]
Sadly no, this is a client side issue
