### ISSUE TITLE
Problem when placing stacks above 64 into chests

### ISSUE THREAD

**Issue by erge1992** [haveric/StackableItems#109]
I've got a problem when putting item stacks above 64 items (stack of 127) into a chest. When I do, it always shows a stack of 64. When I put it back in inventory, it changes back to 127.

How can I fix the number shown in the chest?

Btw: Is there a possibility to increase stacks over 127? Some items (like dirt or cubblestone) need to be stacked higher. I know about this "security feature" against item loss, but is there a possibility?

Thanks in advance

erge1992
![2015-03-31_22 22 13](https://cloud.githubusercontent.com/assets/11743487/6928454/73cb2df4-d7f4-11e4-9597-9fca7333d7ce.png)
![2015-03-31_22 22 21](https://cloud.githubusercontent.com/assets/11743487/6928453/73c8ec74-d7f4-11e4-8e39-dd27e7f84478.png)
![2015-03-31_22 22 23](https://cloud.githubusercontent.com/assets/11743487/6928455/73cb6594-d7f4-11e4-9b20-1cdab47e2ca1.png)

**Comment by haveric** [comment]
This is a vanilla client side issue, I can't control what numbers are displayed. 

Having items over 127 requires handling all items in a custom manner, which is nearly impossible to do. If you attempt to use items over 127 on the server side, you end up with infinite items and stacks that appear as a single item.

**Comment by erge1992** [comment]
Thanks for the really quick answer. This is no problem, just thought, i failed in configuration :-)

**Comment by Wasabules** [comment]
I have exactly the same problem, how you did you?

**Comment by haveric** [comment]
@Wasabules As stated above, this is a vanilla client issue and cannot be fixed within the plugin at this time.
