### ISSUE TITLE
Support for DropsToInventory

### ISSUE THREAD

**Issue by CoolZakCZ** [haveric/StackableItems#110]
Hello, I'm running a prison server, and I have an automatic blocks-to-inventory plugin called DropsToInventory. I'd like to set stacks to be 120, but sadly DropsToInventory only stacks in 64. When I disable the plugin, the blocks worked fine. Would it be possible to add support for DropsToInventory? Or am I just doing something wrong?

**Comment by haveric** [comment]
DropsToInventory would need to hook into StackableItems in order to get the stack amounts and handle it on their side.  If the developer of DropsToInventory is interested in doing this, I can help them out with implementing this, but this isn't something that is possible on the StackableItems side.
