### ISSUE TITLE
problem with brewing_stand

### ISSUE THREAD

**Issue by Brunner2** [haveric/StackableItems#111]
I collect potions up to 64 in my player inventory and chests. But if I have collected bottles and shift-click with brewing_stand window opened, all of 64 potions are placed in the stand. Even if I tried

inventory:
  brewing_stand:
    disabled: true

OR

inventory:
  brewing_stand:
    potion: 1

**Comment by haveric** [comment]
Try using "brewing" instead of "brewing_stand". I should probably document this somewhere if it isn't already. I believe I set this up to use Bukkit's inventory names, which can be confusing at times.
