### ISSUE TITLE
[Duplication] When buy item from shop plugin

### ISSUE THREAD

**Issue by NivixX** [haveric/StackableItems#113]
You can see here how to duplicate

https://youtu.be/6Mbg73ZsD_U?t=2m5s

You can easy get stacked item while there is a limit by buying items from a shop plugin.

**Comment by haveric** [comment]
Can you provide a pastebin of your items.yml file? Are you only able to replicate this by using a shop plugin and which shop plugin are you using?

**Comment by NivixX** [comment]
there is the config :
http://pastebin.com/V9Bw0Pjt
Gold ingot are limited ( max 2 per slots )

You can bypass the stack limit by :

-Buying "goldingot" in Signshop,Chestshop... ( stack limit doesn't work when you use buy plugin )
-Or by using trade plugins like ShopKeeper ( I have a GTA server where you can trade ironingot into Goldingot and the stack limit doesn't work )

When you get your stacked items you can dupe them :
 
1. For exemple you have 32 stacked goldingot ( on your 1st Slot of your inventory ) while there is a limit of 2 lingots
2. you put 4 lingots on all your 4 crafting slot
3. drag your cursor on your 28 other lingots and press "1" ( its an inventory shortcut button ) 
and your lingots will be duplicate

You can see that here : https://youtu.be/6Mbg73ZsD_U?t=2m15s


Sry for my bad english and ty for help.

**Comment by haveric** [comment]
I've handled event priority on my side with the latest release (v1.0.6). If you're still experiencing issues after updating, please create a new ticket.
