### ISSUE TITLE
Stacking in brewing stands

### ISSUE THREAD

**Issue by FoxyFullmoon** [haveric/StackableItems#114]
I'm using StackableItems version 1.0.3

I have potions (water bottles) set to stack to 64 and I have Use_Stack_Amounts_In_Brewing set to false in the config. However, when I drag potions into the brewing stand, whether I left or right click, they're automatically stacking into divided groups. So a stack of 64 sets 21 potions in each slot.

**Comment by haveric** [comment]
"Use_Stack_Amounts_In_Brewing" was removed. Instead, you should use the following:
```
world:
  inventory:
    brewing:
      disabled: true
```
