### ISSUE TITLE
Items spill when double clicking items into inventory

### ISSUE THREAD

**Issue by minoneer** [haveric/StackableItems#116]
We have a strange bug with StackableItems:
Using the minecraft function to shift + double click (with one of the items on cursor) all Items of the same type from a large chest to the player inventory, it usually fills up all empty slots in the player inventory and leaves any remaining stacks inside the chest. However, with this plugin enabled, it spills any items which do not fit in the player inventory to the floor. Strangely, this only happens with certain item types:

Items known to cause this issue:
- cactus green
- bone meal
- cacao
- spruce logs
- red sand
- gray and black stained clay

Items known to work properly
- ink sack
- regular sand
- oak logs
- (default) stone
- cobble stone
- ice
- seeds
- glass

Apparently this is only an issue with items having a damage/data value that is not 0.

StackableItems version: 1.0.4
Spigot version: 1.8.8

Config is set to stack any potions up to 16 globally, only in brewers to 1. All other settings are left to default.

Hope you can look into this and provide a fix, as I would like to continue using this plugin.

Regards, minoneer

**Comment by haveric** [comment]
Outdated issue. Please create a new ticket if you're still experiencing problems with the latest release (v1.0.6)
