### ISSUE TITLE
Exception on 1.9 on item pickup

### ISSUE THREAD

**Issue by minoneer** [haveric/StackableItems#117]
Hey,

when picking up potions (which stack up to 16 on our server), the exception below is thrown. Surprisingly they still stack though:

http://hastebin.com/xojusekati.avrasm

StackableItems: Version: 1.0.4
Spigot: CraftBukkit version git-Spigot-3104eb1-68b7277 (MC: 1.9)

**Comment by haveric** [comment]
I'll be looking into updating StackableItems to 1.9 this weekend. If it is only this issue (Sound enum changed), it should be a quick update.

**Comment by minoneer** [comment]
Great, everything else seems to work so far.

**Comment by MomaCods** [comment]
Does the beetroot soup stack or will that be once its updated to 1.9?
