### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by zenandreas** [haveric/StackableItems#118]
Hello,

Altough the console logs show no error, it does not work. Here is my config: ( running paperspigot 1.8 )

allWorlds:
  default:
    MIN: 32
    MAX: 100
  player: {}
  group:
    admin:
      MIN: 100
      MAX: 100
  inventory:
    chest:
      MIN: 100
      MAX: 100
Enelloth: ( main world )
  default:
    MIN: 100
    MAX: 100

**Comment by haveric** [comment]
Plugin seems to work fine with this config setup. Make sure you are not in creative mode when testing the stacking.

**Comment by zenandreas** [comment]
That was so simple, thanks !
