### ISSUE TITLE
InventoryClickEvent error with potions

### ISSUE THREAD

**Issue by TheBentoBox** [haveric/StackableItems#119]
Hey.

Getting a stack trace appearing for click events with potions. I'm not really sure what causes it, it seems inconsistent. [Stack trace](http://pastebin.com/69z01jLJ).

**Comment by haveric** [comment]
Are you still getting these errors on the latest Bukkit/Spigot? This seems like something that might have been a Bukkit/Spigot bug with the new potion mechanics.
