### ISSUE TITLE
Item duplication

### ISSUE THREAD

**Issue by TheBentoBox** [haveric/StackableItems#121]
I know this is basically the absolute worst kind of ticket I could give you, because I have no error report and reproducing it is sort of vague/random. Basically, players were able to somewhat reliably duplicate stackable items (obviously only those made stackable by the plugin) just by rapidly clicking back and forth between their inventory and a chest. They basically did random actions like right clicking to split stack, shift clicking the rest in, placing some, etc. etc. I didn't get to reproduce it myself (I uninstalled), but I physically watched a player turn 16 potions into 19 potions, and was in voice chat with him at the time. Another player did the same thing with horse armor and minecarts shortly afterwards.

I don't know what else to tell you, it's not throwing errors or anything when it does it of course. I figured I should open an issue just to at least explain my experience, even if there's not much you can do to help with the very little info I have.

**Comment by haveric** [comment]
I've had other reports similar to this, but have never been able to replicate it as anything other than ghost items. If you're able to find a repeatable method of having this happen, I could help more.  I suppose it might be possible if the server is being stressed and not able to keep up, but I've not been able to confirm that as the cause.

**Comment by TheBentoBox** [comment]
I understand, I'll see if I can get any more concrete info about how to replicate it. I've also had issues replicating it even though I've watched players do so.

**Comment by Lazini** [comment]
I can confirm this problem, _Minecraft: 1.9.1, StackableItems 1.0.5 for 1.9_

To replicate this, enable the plugin for minecarts. Then place a minecart on a rail track. Break the minecart and **two** minecart items will be dropped.

**Comment by Jnxd1** [comment]
I also have encountered the same issue.
My players can do it with anvils.

1) Place 2 items in the anvil (my case ench books)
2) Hover over one of the books in the anvil and Press and HOLD Keyboard Key 1 (example)
3) Don't stop pressing they Key 1 and start to hover with the mouse over the 2 items in the anvil
4) If you can not make it work.Just start the process all over.You will eventually make it work.

**Comment by haveric** [comment]
I haven't been able to replicate this. If it's still happening in v1.0.6, please create a new ticket as much detail as you can.
