### ISSUE TITLE
ChestCommands conflict

### ISSUE THREAD

**Issue by vicknyaz112** [haveric/StackableItems#122]
There is a problem with ChestCommands (and all other inventories, which you are not supposed to take items from).
When a player presses a number key, hovering the mouse over an item in such an inventory, and has any item in appropriate slot of their inventory (for example, they press 4 key and they have an item in forth slot), the item will be moved to their inventory (although it is not supposed to).
This issue only seems to be happening when StackableItems is running.

Thanks for the help and the awesome plugin!

**Comment by haveric** [comment]
Closing as issue was fixed on CrateReloaded side and no updates since.
