### ISSUE TITLE
Issue With Comparators Not Changing Power With Stacked Potions

### ISSUE THREAD

**Issue by Schneiderism** [haveric/StackableItems#124]
So I set item ID 373 [Potion] to stack with sizes of two so I could feed them through an item sorters. Non-stackable items have a power output of 3 blocks per item. When I put two potions into it without stacking them, the signal goes 6 blocks like normal. However, when I put the stack of two potions into the hopper, the output remains at three. Is there a way to fix this? No matter how many stacks of two I put into the hopper, the output never changes. However, an oddity I did notice is that if I put in a stack of two, followed by four individual bottles, the output sits at three, but when I take one potion from the stack of two, the output suddenly jumps up the the full output because the hopper recognizes that it's full. Any solutions?

**Comment by haveric** [comment]
I doubt there's anyway to change this as I'm not actually changing the max stack size that the server knows about (nor can I) and I would assume comparator results are tied to those. If anyone knows any solutions, please let me know.

**Comment by haveric** [comment]
As far as I'm aware, this still isn't possible, so I'm closing the ticket as unfixable.
