### ISSUE TITLE
CrateReloaded Confliction

### ISSUE THREAD

**Issue by imWillX** [haveric/StackableItems#125]
Hello there,

Seems like this plugin is conflicting with my plugin, CrateReloaded. It appears this isn't the only plugin it is conflicting with as I have seen reports for Chest Commands and a certain Shop plugin. 

Users are allowed to grab items out of inventories as described in #122 and #113. Currently I am out of town otherwise I would take a look and submit a pull request. If you need any more information, please let me know.

**Comment by haveric** [comment]
This is likely an event priority issue. I am using EventPriority.HIGHEST to let my plugin run after any others as long as the event isn't cancelled. As long as your plugin (and any others that handle custom inventories has a lower priority and cancels the event, they will take priority.  If this isn't the issue, please feel free to submit a pull request.

**Comment by imWillX** [comment]
Issued a fix on my end. If there are any issues, will reopen.
