### ISSUE TITLE
Click support

### ISSUE THREAD

**Issue by Lemrigue** [haveric/StackableItems#126]
When you have 64 dirt in your inventory and try to take other dirt with the click and put it in the 64, they won't be added to the 64. You have to drop it on the ground and take it to be added to the 64

**Comment by haveric** [comment]
Are you in creative or survival? Creative has limited control over inventory events, but survival should be working as intended.

**Comment by Lemrigue** [comment]
Oh yeah you are right, it works fine in survival, I was in creative when I test it, thanks
