### ISSUE TITLE
items deleting

### ISSUE THREAD

**Issue by Zanzoman** [haveric/StackableItems#132]
Stackableitems 1.0.5 
Minecraft 1.12.2

Overlapping a damaged diamond sword and a non damaged diamond sword will void one of the two items.

Btw anyone able to help me with what the config for a diamond sword with stack of 64, and diamond sword damage value 120 with stack of 64 should look like. Big help.
Thanks

**Comment by WhyDoWeWonder** [comment]
I may not be the plugin developer but could you give me more details, what you're describing is quite unclear.

**Comment by haveric** [comment]
There's not enough detail to determine what this issue is. If you're still experiencing issues after updating to v1.0.6, please create a ticket with as much detail as you can.
