### ISSUE TITLE
Could not pass event FurnaceSmeltEvent to StackableItems v1.0.6

### ISSUE THREAD

**Issue by Maelep** [haveric/StackableItems#136]
Server: PaperMC 1.14.4 #171
Plugin: StackableItems 1.0.6

`15.08 23:13:55 [Server] ERROR Could not pass event FurnaceSmeltEvent to StackableItems v1.0.6
15.08 23:13:55 [Server] INFO java.lang.ClassCastException: org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock cannot be cast to org.bukkit.block.Furnace
15.08 23:13:55 [Server] INFO at haveric.stackableItems.listeners.SIPlayerListener.furnaceSmelt(SIPlayerListener.java:64) ~[?:?]
15.08 23:13:55 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor63.execute(Unknown Source) ~[?:?]
15.08 23:13:55 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-171]
15.08 23:13:55 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-171]
15.08 23:13:55 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-171]
15.08 23:13:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-171]
15.08 23:13:55 [Server] INFO at net.minecraft.server.v1_14_R1.TileEntityFurnace.burn(TileEntityFurnace.java:345) ~[patched_1.14.4.jar:git-Paper-171]
15.08 23:13:55 [Server] INFO at net.minecraft.server.v1_14_R1.TileEntityFurnace.tick(TileEntityFurnace.java:298) ~[patched_1.14.4.jar:git-Paper-171]
15.08 23:13:55 [Server] INFO at net.minecraft.server.v1_14_R1.World.tickBlockEntities(World.java:856) ~[patched_1.14.4.jar:git-Paper-171]
15.08 23:13:55 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:382) ~[patched_1.14.4.jar:git-Paper-171]
15.08 23:13:55 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[patched_1.14.4.jar:git-Paper-171]
15.08 23:13:55 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-171]
15.08 23:13:55 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-171]
15.08 23:13:55 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-171]
15.08 23:13:55 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

**Comment by haveric** [comment]
Thanks, this has been fixed in v1.0.7
