### ISSUE TITLE
Items don't automatically stack

### ISSUE THREAD

**Issue by Maelep** [haveric/StackableItems#137]
Can you make that items automatically stacks when updated?

Example:
I made Potion stackable so filling a Glass Bottle with water create one stack of one option and if I fill one more Glass Bottle it create one other stack of one option. I have to sort manually my items.

**Comment by haveric** [comment]
That is the goal of the plugin, but as you've found, there are some cases that are not covered yet. I'll certainly look into glass bottle filling and see what I can do.

**Comment by Maelep** [comment]
I think that will be the same issue with bucket, water bucket and lava bucket :)

**Comment by haveric** [comment]
Those are already supported

**Comment by haveric** [comment]
Water bottle filling has been fixed in v1.0.8
