### ISSUE TITLE
Stacks unstacking and replacing items in shulker boxes

### ISSUE THREAD

**Issue by FatherWh0** [haveric/StackableItems#141]
This is an issue where stacked items in a shulker box will unstack and replace other items.
To reproduce:
Allow cakes (for example) to stack to 64 in both inventory and chests.
Place a stack of 64 cakes in the upper-left square of a shulker box.
Fill the other squares with any other items.
Break the shulker box.
Place and reopen the shulker box.
The cakes will have unstacked and replaced the items to the right of them.
Stackableitems version 1.0.9
Paper version 1.14.4

**Comment by haveric** [comment]
Confirmed that it's shifting contents to the right. Just to confirm, are you wanting cakes to stack in shulker boxes in the first place?

**Comment by haveric** [comment]
Also, if you could jump on discord or provide your items.yml config, that would be helpful.

**Comment by FatherWh0** [comment]
Yes, adding stacking support for shulker boxes is probably the best fix for this issue but it's not critical that shulker boxes allow stacking as long as they don't remove items like they do now.
[items.zip](https://github.com/haveric/StackableItems/files/3604155/items.zip)

**Comment by haveric** [comment]
Can you try out the following [dev build](https://cdn.discordapp.com/attachments/608396088436588551/622145300122959901/StackableItems.jar) and let me know if it fixes your issues?

**Comment by FatherWh0** [comment]
That appears to have fixed it. :)

**Comment by haveric** [comment]
This is fixed as of v1.0.10

If you're still experiencing any issues after updating, please create a new ticket with as much information as you can.
