### ISSUE TITLE
Shulker box stacks can be placed in other shulker boxes

### ISSUE THREAD

**Issue by ac101m** [haveric/StackableItems#143]
We use this plugin on our paperspigot server solely for empty shulker box stacking.
One of our users recently accidentally placed some stacked shulker boxes inside another shulker box. This should not be possible.
The incident resulted in the loss of the shulker boxes, as a result of #141

**Comment by haveric** [comment]
Confirmed and should have this fixed in the next release.

**Comment by ac101m** [comment]
Awesome! Thanks a bunch :)

**Comment by ac101m** [comment]
I noticed a couple days ago you made commits to fix this and #141 
Any eta on a release with those fixes in it? We just had another accident on our server

**Comment by haveric** [comment]
I tend not to provide etas when I'm in the middle of updates as it's too easy to let them slip. Best I can say is soon. With that said, I will try to get a stable devbuild out tomorrow on [discord](https://discordapp.com/invite/3JY9JC3) with the current state of updates.

**Comment by haveric** [comment]
This is fixed as of v1.0.10

If you're still experiencing any issues after updating, please create a new ticket with as much information as you can.
