### ISSUE TITLE
Support for 1.12.2 and below

### ISSUE THREAD

**Issue by portlek** [haveric/StackableItems#150]
`java.lang.NoClassDefFoundError: org/bukkit/block/data/BlockData`
There is no any class like that in 1.12.2 and below so, this plugin should check the version.

**Comment by haveric** [comment]
StackableItems does not support 1.12. Due to the complexity of the plugin, I do not plan on supporting older versions anymore. It became too complex trying to support multiple versions and all of the differences between them.

**Comment by haveric** [comment]
No there is not.

**Comment by RobinRMC** [comment]
:(
