### ISSUE TITLE
Unable to pick up items from ground with >64 stacks in inventory

### ISSUE THREAD

**Issue by martinambrus** [haveric/StackableItems#157]
I set max stacks to 127, I have a full inventory of blocks and a stack of 121 torches. I put a torch on a block, destroy it and I'm unable to pick it up again, even though I only have 120 torches in inventory slot. It should be possible to pick up 7 more torches in this case.

**Comment by haveric** [comment]
Unfortunately, the EntityPickupItemEvent does not get fired when it thinks the stacks are all full so I have no control over allowing items to be picked up in this instance. The only other solution would require handling all item pickups manually, which would likely be poor on performance and break any other plugins using that API event.

**Comment by martinambrus** [comment]
Is this similar to why furnaces are unable to smelt more than 64 items, or is that a different issue?

**Comment by haveric** [comment]
A lot of the game is handled client side and/or not designed for anything above 64, hence the inconsistent behavior.
