### ISSUE TITLE
Lava disappear in cauldrons

### ISSUE THREAD

**Issue by deREALshocK** [haveric/StackableItems#163]
When you set Lava Bucket to stackable e.g. 64 and you try to put lava in a cauldron the lava disappear and the cauldron is still empty.
and when you got a cauldron full of lava and try to get a bucket out of it, you get water :D

**Comment by haveric** [comment]
There is a dev-build (1.0.12-dev2) on the discord that fixed stacking issues for cauldrons, although I did just see a change in spigot that may break that again, specifically for lava cauldrons. Please let me know if you're still experiencing this issue on the dev-build.

**Comment by deREALshocK** [comment]
thx for the fast reply, thats awesome i will test it and will keep you up to date :)

**Comment by deREALshocK** [comment]
Now the cauldron dont get filled again by dripstone when you get a bucket of lava from it.
after replacing the cauldron, it get filled again.
so you need to replace the cauldron everytime when you take a bucket of lava from it.
no matter if it stacked or just one bucket.

**Comment by deREALshocK** [comment]
Bug is fixed in the new dev-build, thanks

**Comment by catronomix** [comment]
I downloaded the dev build for my server and it was fixed, but after the last spigot update it broke again it seems.

**Comment by catronomix** [comment]
Where does one find this dev build? Is this plugin still in active development?

**Comment by haveric** [comment]
Dev builds are on the discord: https://discord.gg/3JY9JC3

A lot of things have kept me busy and I haven't gotten back to updating these plugins. Hoping to find some time soon to do so.

**Comment by haveric** [comment]
This is officially fixed with v1.1.0
