### ISSUE TITLE
Stacked potions can be placed in brewing stand with stack limitations.

### ISSUE THREAD

**Issue by Noobly-Walker** [haveric/StackableItems#181]
If I set potions to stack to 16 by default, even if I make an override for brewing stands to only stack 1, placing stacked potions by left or right-clicking in a brewing stand slot sometimes places the whole stack instead of just one.

**Comment by haveric** [comment]
I haven't been able to replicate this issue. If you're still experiencing it, please let me know and provide your current configuration and any steps you can to help replicate it.

**Comment by Noobly-Walker** [comment]
I don't think I've changed my config settings for this plugin since the last time I was asked.
data/blastfurnaces.yml: default (blank)
data/furnaces.yml: default (blank)
data/smokers.yml: default (blank)
lists/customfuel.txt: default (blank)
furnaceXP.yml: default
groups.yml: default (blank)
items.yml: potions stack to 16 in the inventory or most containers, but to 1 in brewing stands so people can't make 48 potions from simple ingredients.
options.yml: default

![potion_stack_issue](https://github.com/haveric/StackableItems/assets/59349202/2d526dd6-4201-4751-bab9-b9ebb63a5d91)
As you can see from this gif recording, it is by no means consistent, and does not, at least to my knowledge, involve any previously recorded bugs.

**Comment by Noobly-Walker** [comment]
If you need more information on my server, let me know.

**Comment by haveric** [comment]
I am starting to wonder if this is something server specific. Your gif looks like it might be the drag to place multiple action causing it, but I can't get it to happen on my end.

For testing purposes, can you replicate this by taking a stack of potions and dragging it within a single slot in order to drop it? For my ability to test this though, would you be able to zip up your server and send it to me so that I can test the exact setup you have?

**Comment by Noobly-Walker** [comment]
You seem to be correct, dragging a stack of potions across a single slot, then releasing it, does cause the entire stack to enter the slot.

I am making a server backup now. It is on the order of several gigabytes, so it will take a while.

**Comment by haveric** [comment]
> I am making a server backup now. It is on the order of several gigabytes, so it will take a while.

Feel free to exclude the worlds folders to help reduce file size

**Comment by Noobly-Walker** [comment]
https://drive.google.com/file/d/13son2BE0wOXWZGm3HHZvsLI-5DZ_h_Tj/view?usp=sharing

**Comment by haveric** [comment]
Looks like it's private, but I've requested permission on it. Alternatively, you can make it public.

**Comment by Noobly-Walker** [comment]
My apologies. I don't use Google Drive much.

**Comment by haveric** [comment]
Can you try changing your configuration from "brewing_stand" to "brewing":
```
    brewing_stand: #Override for brewing stand
      potion: 1
      splash_potion: 1
      lingering_potion: 1
```
      
to

```
    brewing: #Override for brewing stand
      potion: 1
      splash_potion: 1
      lingering_potion: 1
```

**Comment by Noobly-Walker** [comment]
Alright, I'll check to see if that solves the issue.

**Comment by Noobly-Walker** [comment]
That seems to have fixed it. Thanks!
I had thought that CRAFTING_TABLE and BREWING_STAND were valid inventory types, but after re-examining spigot's documentation, I can say for certain that they were not. I don't know where I got those from. Assuming, probably.

**Comment by haveric** [comment]
I think the confusion is that those are valid Material types, where this is looking for Inventory types, which of course are slightly different.
