### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by hmlendea** [haveric/StackableItems#186]
Hello.

I see that there were many merges done on the master branch since the last release, dated 20 June 2022.

Are you planning to release those changes? Or is there anywhere I can download an up-to-date jar?

Thank you.

**Comment by haveric** [comment]
Unfortunately, real life got in the way before I could complete testing of the latest changes needed before I can do a release. I'm hoping to find the time to get these out in the near future, but from what I recall, there were some issues I was running into that still needed investigation.

**Comment by hmlendea** [comment]
Understood. In the meantime І՝m using the latest release and it works fine for the most part. Some items (that are unstackable in vanilla) cause issue with (even accidental) duplication but I`ve just marked them as mаxіmum stack of one. If this could be fix it would be great, otherwise just blocks working is fine also (I use 126 stacks as thаt`ѕ an even number and it works fine)

**Comment by haveric** [comment]
> Some items (that are unstackable in vanilla) cause issue with (even accidental) duplication but I’ve just marked them as mаxіmum stack of one. If this could be fix it would be great, otherwise just blocks working is fine also (I use 126 stacks as thаt`ѕ an even number and it works fine)

If you do find issues like this and can replicate them, please do create issues or let me know on discord with as much detail as you can. It's hard to make everything work perfectly with a plugin like this, but it's always good to know if there are things that need more investigation and things sometimes get overlooked trying to cover everything. Worst case scenario, I can get a dev build released out on discord with recent fixes after a much smaller amount of testing.

**Comment by haveric** [comment]
A dev build has been released on the [discord](https://discord.gg/3JY9JC3) (v1.2.0-dev1) in the si-devbuilds channel. Please let me know if you get a chance to test it or run into any issues with it.
